name: Bump Version

on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }} # checkout the PR branch

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        check-latest: true

    - name: Install dependencies
      run: |
        pip install setuptools

    - name: Bump version
      run: |
        CURRENT_VERSION=$(grep -oP '(?<=version=")[^"]*' setup.py)
        echo "Current version: $CURRENT_VERSION"
        
        MAJOR_MINOR=$(echo $CURRENT_VERSION | cut -d. -f1,2)
        NEW_VERSION="${MAJOR_MINOR}.${{ github.run_number }}${{ github.run_attempt }}"
        echo "New version: $NEW_VERSION"

        sed -i "s/version=['\"]$CURRENT_VERSION['\"]/version=\"$NEW_VERSION\"/" setup.py
    
    - name: Commit and push new version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ github.workspace }}/setup.py"
        git commit -m "Bump version to $NEW_VERSION"
        git push origin ${{ github.head_ref }}

    - name: Comment on the PR with the new version
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "Bumped version in setup.py."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}